### ISSUE TITLE
Memory Error loading Level 2 on iPad Air (iOS 8.1.3) 

### ISSUE THREAD

**Issue by x2apps** [jocelynlih/SwiftGameBook#138]
Incident Identifier: 252C6677-5275-424E-8044-B0E739387723
CrashReporter Key:   5d78c5f7e80851c92c4416e9c5c7a6a3245a595b
Hardware Model:      iPad4,1
OS Version:          iPhone OS 8.1.3 (12B466)
Kernel Version:      Darwin Kernel Version 14.0.0: Mon Jan 12 21:30:00 PST 2015; root:xnu-2783.3.26~3/RELEASE_ARM64_S5L8960X
Date:                2015-02-05 17:31:48 -0700
Time since snapshot: 159 ms

Free pages:                              1700
Active pages:                            103798
Inactive pages:                          52220
Speculative pages:                       100
Throttled pages:                         0
Purgeable pages:                         2
Wired pages:                             57559
File-backed pages:                       48899
Anonymous pages:                         107219
Compressions:                            1188602
Decompressions:                          135299
Compressor Size:                         34419
Uncompressed Pages in Compressor:        149462
Page Size:                               16384
Largest process:   PencilAdventure

This is new with iOS 8.1.3. The game worked fine until the 8.1.3 upgrade.

**Comment by ankurp** [comment]
Let us take a look. Thanks for sharing

**Comment by x2apps** [comment]
I deleted a couple of signs in the 2.sks and got the level 2 to work, but there are still memory warnings in the console for Level 2. Levels 3 and 4 work fine. Thanks for a fun learning game.
